services:
  - type: web
    name: ytanalytics
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --timeout 120
    envVars:
      - key: SITE_PASSWORD
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: DATA_URL
        sync: false
      - key: PYTHON_VERSION
        value: 3.12.3
